org.gradle.jvmargs=-Xmx32G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]

forge_version=47.4.10
forge_version_range=[47,)

loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=flooded
mod_name=Flooded
mod_license=mod_license=GNU General Public License v3
mod_version=0.0.0.1
mod_group_id=fi.dy.masa
mod_authors=masa, TheModpackCurator
mod_description=Flooded
