modLoader="javafml"
loaderVersion="${loader_version_range}"
license="mod_license=GNU General Public License v3"

[[mods]]
modId="flooded"
version="${mod_version}"
displayName="Flooded-Refabricated"
displayURL = "https://modrinth.com/mod/flooded-refabricated"
credits="Original Flooded mod by masa, updated to 1.20.1 by TheModpackCurator"
authors="${mod_authors}"

description='''
It's raining. The water level is rising... brought to 1.20.1!!!
'''

[[dependencies.flooded]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.flooded]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
